#!/bin/bash
set -e
ENV_FILE=".env"
ENV_FILE_TEMPLATE=".env.template"

if [ -z "$CI" ] && [ ! -f "$ENV_FILE" ]
then
    cp -v "$ENV_FILE_TEMPLATE" "$ENV_FILE"
    echo "Make sure to edit $ENV_FILE and run $0 again"
    exit 0
fi

if [ -z "$CI" ]
then
    dropdb "stampdown" || echo "db did not exist"
    createdb "stampdown"
fi

./manage.py migrate
./manage.py seeddb
